server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/retail
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:TestTest}
  application:
    name: JpaStreamerExample
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
       ddl-auto: update